version: 1.0.0.{build}
os: Visual Studio 2017
configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
  - cmd: dotnet restore "src/SysCommand.Tests.UnitTests.DotNetCore/SysCommand.Tests.UnitTests.DotNetCore.csproj"